name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: [lint-frontend, lint-backend]
    runs-on: ubuntu-latest
    concurrency:
      group: deploy
      cancel-in-progress: true
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          host_fingerprint: ${{ secrets.SSH_FINGERPRINT }}
          command: source ~/.nvm/nvm.sh; echo 'Hello Kirill'
